#!/usr/bin/env python3
"""Contact-graph merge feed — A64.

Writes store/li_graph_nodes.jsonl: one row per distinct LinkedIn contact this
system has ever touched, in a shape agents/contact_graph.py's build_graph()
could consume as a FOURTH source (alongside its existing GHL/jobs/replies
sources) — WITHOUT editing contact_graph.py (out of this lane's scope). See
the CONTRACT section below for the exact one addition that file's owner would
make.

Why a separate file rather than writing into contact_graph.json directly:
contact_graph.py's OUT (store/contact_graph.json) is a full-overwrite build
artifact regenerated by build_graph() every run — writing into it directly
from this lane would either get clobbered on the next contact_graph.py run or
require this lane to fight over write ownership of a file it doesn't own.
Feeding a normalized jsonl that contact_graph.py's OWNER can wire in as a new
source (same pattern its jobs.jsonl/replies.jsonl sources already use) is the
non-destructive way to contribute LinkedIn identity data to the unified graph.

Person.to_dict() shape (from contact_graph.py, read directly, not duplicated
by import to avoid a cross-lane dependency): {"name", "emails": [], "phones":
[], "sources": [], "tags": []}. LinkedIn contacts have NO email/phone captured
in this system (LinkedIn doesn't expose them without a mutual connection
accepting first, and this system never scrapes that), so li_graph_nodes.jsonl
rows carry "url" as the join key instead — contact_graph.py's owner would need
to add name-based OR url-based joining for this source (documented in the
CONTRACT, this file doesn't invent that logic since it's not this lane's file
to change).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for p in (ROOT, ROOT / "app", ROOT / "agents"):
    sys.path.insert(0, str(p))
from store_lib import now_iso  # noqa: E402
import networking  # noqa: E402
import li_history  # noqa: E402

OUT = ROOT / "store" / "li_graph_nodes.jsonl"


def build_nodes() -> list[dict]:
    """One node per distinct URL in networking's full history (any status),
    tagged with every kind of touch this system has made (comment/connect/
    like/reply/dm) and the CURRENT best-known status (e.g. 'connected' is
    approximated as: a connect item exists with status done — LinkedIn gives
    no stronger signal without operator-fed accepted.jsonl data, so this
    stays a soft signal, never a hard claim of 1st-degree connection)."""
    by_url: dict[str, dict] = {}
    for rec in networking.load_queue():
        url = rec.get("url", "")
        if not url:
            continue
        uk = li_history._url_key(url)
        node = by_url.setdefault(uk, {"url": url, "name": "", "kinds": set(),
                                       "touch_count": 0, "connect_done": False})
        if rec.get("author") and not node["name"]:
            node["name"] = rec["author"]
        node["kinds"].add(rec.get("kind", ""))
        node["touch_count"] += 1
        if rec.get("kind") == "connect" and rec.get("status") == "done":
            node["connect_done"] = True

    nodes = []
    for uk, n in by_url.items():
        nodes.append({
            "url": n["url"], "name": n["name"],
            "kinds": sorted(k for k in n["kinds"] if k),
            "touch_count": n["touch_count"],
            "soft_connected": n["connect_done"],
            "source": "linkedin",
        })
    nodes.sort(key=lambda n: n["name"].lower())
    return nodes


def run() -> int:
    nodes = build_nodes()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        for n in nodes:
            f.write(json.dumps(n, ensure_ascii=False) + "\n")
    print(f"li_graph: {len(nodes)} LinkedIn contact node(s) -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
