#!/usr/bin/env python3
"""J183: prompt inventory generator. Every agent in agents/ writes its LLM prompts as a
module-level ALL_CAPS = \"\"\"...\"\"\" (or f\"\"\"...\"\"\") string constant — that's the one
convention every agent in this codebase already follows (verified by grep before writing
this). Extracting those into a separate prompts/ directory would mean two sources of truth
(the agent's own file, plus a copy) drifting apart silently, so this tool does NOT move
prompts out of their owning agent. Instead it greps agents/*.py for that pattern and writes
a generated catalog (prompts/INVENTORY.md) with file:line references, so "what prompts exist
and where" is answerable in one file without touching 79 agent files.

Detection pattern: a line at column 0 matching
  NAME = \"\"\"   or   NAME = f\"\"\"   or   NAME: str = \"\"\"
where NAME is ALL_CAPS/underscore/digits (the convention every prompt constant in this
codebase follows — CLASSIFY, PROMPT, GEN, BUILD_PROMPT, PLAN_PROMPT, SYSTEM, INTERPRET, etc).
The catalog records the constant name, owning file, line number, and a one-line preview
(first non-empty line of the string, truncated).

Usage:
  tools/prompt_inventory.py           # scan agents/, write prompts/INVENTORY.md, print summary
  tools/prompt_inventory.py --check   # scan + exit 1 if INVENTORY.md would change (CI-style)
"""
from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / "agents"
APP_DIR = ROOT / "app"
OUT = ROOT / "prompts" / "INVENTORY.md"

# NAME = """   or   NAME = f"""   or   NAME: str = """    (also single-quote """ variant '''
DECL_RE = re.compile(
    r'^([A-Z][A-Z0-9_]*)\s*(?::\s*str)?\s*=\s*f?("""|\'\'\')'
)


def _preview(text: str, max_chars: int = 110) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line:
            return (line[:max_chars] + "...") if len(line) > max_chars else line
    return "(empty)"


def scan_file(path: Path) -> list[dict]:
    lines = path.read_text(errors="replace").splitlines()
    hits = []
    i = 0
    while i < len(lines):
        m = DECL_RE.match(lines[i])
        if m:
            name, quote = m.group(1), m.group(2)
            # gather the string body until the closing triple-quote (may be same line)
            rest_of_line = lines[i].split(quote, 1)[1] if quote in lines[i] else ""
            body_lines = [rest_of_line]
            closed = quote in rest_of_line
            j = i
            while not closed and j + 1 < len(lines):
                j += 1
                if quote in lines[j]:
                    body_lines.append(lines[j].split(quote, 1)[0])
                    closed = True
                else:
                    body_lines.append(lines[j])
            body = "\n".join(body_lines)
            hits.append({
                "name": name, "file": path, "line": i + 1,
                "end_line": j + 1, "preview": _preview(body),
                "chars": len(body),
            })
            i = j
        i += 1
    return hits


def scan_dirs(dirs: list[Path]) -> list[dict]:
    hits = []
    for d in dirs:
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.py")):
            hits.extend(scan_file(path))
    return hits


def render_markdown(hits: list[dict]) -> str:
    lines = [
        "# Prompt inventory (generated)",
        "",
        f"Generated by `tools/prompt_inventory.py` on {datetime.now().astimezone().isoformat(timespec='seconds')}.",
        "DO NOT hand-edit this file, rerun the script instead — it is a catalog, not a source",
        "of truth. Each prompt LIVES in its owning agent file; this file only indexes them",
        "(file:line + a one-line preview) so \"what prompts exist and where\" is answerable",
        "without opening 79 files.",
        "",
        f"**{len(hits)} prompt constant(s) found** across "
        f"{len({h['file'] for h in hits})} file(s).",
        "",
        "| Constant | File:Line | Chars | Preview |",
        "|---|---|---|---|",
    ]
    for h in sorted(hits, key=lambda h: (str(h["file"]), h["line"])):
        rel = h["file"].relative_to(ROOT)
        preview = h["preview"].replace("|", "\\|")
        lines.append(f"| `{h['name']}` | `{rel}:{h['line']}` | {h['chars']} | {preview} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                     help="scan and exit 1 if prompts/INVENTORY.md would change, without writing")
    a = ap.parse_args()

    hits = scan_dirs([AGENTS_DIR, APP_DIR])
    rendered = render_markdown(hits)

    if a.check:
        current = OUT.read_text() if OUT.is_file() else ""
        # ignore the "Generated by ... on <timestamp>" line when diffing for --check
        strip_ts = lambda s: re.sub(r"on \d{4}-\d{2}-\d{2}T[\d:+-]+\.", "on <ts>.", s)
        if strip_ts(current) != strip_ts(rendered):
            print("prompt_inventory --check: FAIL, prompts/INVENTORY.md is stale (rerun without --check)")
            return 1
        print("prompt_inventory --check: PASS, prompts/INVENTORY.md is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    print(f"prompt_inventory: found {len(hits)} prompt constant(s) across "
          f"{len({h['file'] for h in hits})} file(s), wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
